CREATE TABLE IF NOT EXISTS mock_payments (
    attempt_key VARCHAR(100) PRIMARY KEY,
    amount NUMERIC(19, 0) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    status VARCHAR(20) NOT NULL,
    transaction_id VARCHAR(100),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS mock_refunds (
    refund_key VARCHAR(100) PRIMARY KEY,
    attempt_key VARCHAR(100) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
