ALTER TABLE users
    ADD COLUMN last_modified_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE events
    ADD COLUMN last_modified_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE ticket_grades
    ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN last_modified_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;
